import type { Dog, DogUpdate, Sponsorship } from '../types';

export const mockDogs: Dog[] = [
  {
    id: 'dog-1',
    name: 'Max',
    description: 'O Max é um cão cruzado de Golden alegre e enérgico que adora correr na relva e brincar com a bola. Foi encontrado abandonado num campo rural. Embora seja parcialmente cego do olho esquerdo, isso não o impede de ser o cão mais amigável do abrigo. Precisa de um padrinho para ajudar a cobrir a sua ração de alta qualidade e o tratamento diário com gotas nos olhos.',
    breed: 'Cruzado de Golden Retriever',
    age: '3 anos',
    gender: 'male',
    status: 'partially_sponsored',
    targetMonthlySponsorship: 30,
    currentMonthlySponsorship: 10,
    mainImageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Gotas diárias para gerir a secura ocular e a pressão (€15/mês).',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dog-2',
    name: 'Luna',
    description: 'A Luna é uma sénior muito dócil que adora dormir ao sol e dar passeios lentos e tranquilos. Passou toda a sua vida acorrentada antes de ser resgatada pelo nosso abrigo. Sofre de osteoartrite grave nas ancas, o que torna as caminhadas dolorosas sem medicação. Apoiar a Luna vai ajudar-nos a garantir o seu anti-inflamatório diário e suplementos articulares.',
    breed: 'Cruzada de Labrador',
    age: '8 anos',
    gender: 'female',
    status: 'needs_sponsor',
    targetMonthlySponsorship: 40,
    currentMonthlySponsorship: 0,
    mainImageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Medicação diária para a dor e suplementos articulares premium (€30/mês).',
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dog-3',
    name: 'Rocky',
    description: 'O Rocky é um jovem valente e cheio de vida. Foi atropelado por um carro enquanto vivia na rua e sofreu uma fratura no fémur. Graças ao nosso fundo de emergência, recebeu uma cirurgia ortopédica bem-sucedida. Encontra-se em recuperação e necessita de consultas veterinárias regulares e sessões de fisioterapia para recuperar a força na pata. Ajude o Rocky a voltar a correr!',
    breed: 'Sem Raça Definida (Rafeiro)',
    age: '1 ano',
    gender: 'male',
    status: 'fully_sponsored',
    targetMonthlySponsorship: 50,
    currentMonthlySponsorship: 50,
    mainImageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Consultas veterinárias mensais, radiografias e sessões de fisioterapia (€45/mês).',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dog-4',
    name: 'Toby',
    description: 'O Toby foi resgatado de uma situação de acumulação animal juntamente com outros 20 cães. Como resultado, tem muito medo de humanos e ruídos fortes. Ainda não está pronto para adoção, mas trabalha diariamente com um terapeuta comportamental para aprender a confiar novamente. Apadrinhar o Toby ajuda a financiar as suas sessões de treino especializado e coleiras difusoras de feromonas calmantes.',
    breed: 'Cruzado de Beagle',
    age: '5 anos',
    gender: 'male',
    status: 'needs_sponsor',
    targetMonthlySponsorship: 30,
    currentMonthlySponsorship: 0,
    mainImageUrl: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Sessões semanais com um terapeuta comportamental especializado e suplementos calmantes.',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dog-5',
    name: 'Bella',
    description: 'A Bella é uma bulldog francês muito dócil que foi entregue ao abrigo porque os antigos donos não conseguiam suportar os seus custos veterinários. Como muitos cães da sua raça, sofre de problemas respiratórios graves (síndrome braquicefálica) e necessita de uma ração especial para prevenir alergias de pele crónicas. Precisa de um padrinho para ajudar a pagar a sua ração hipoalergénica de prescrição médica.',
    breed: 'Bulldog Francês',
    age: '6 years',
    gender: 'female',
    status: 'partially_sponsored',
    targetMonthlySponsorship: 40,
    currentMonthlySponsorship: 20,
    mainImageUrl: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Alimentação especial hipoalergénica (€40/mês) e banhos semanais com champô medicado.',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const mockSponsorships: Sponsorship[] = [
  {
    id: 'spons-1',
    dogId: 'dog-1',
    sponsorName: 'Ana Silva',
    sponsorEmail: 'ana.silva@exemplo.com',
    monthlyAmount: 10,
    status: 'active',
    startDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spons-2',
    dogId: 'dog-3',
    sponsorName: 'João Santos',
    sponsorEmail: 'joao.santos@exemplo.com',
    monthlyAmount: 25,
    status: 'active',
    startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spons-3',
    dogId: 'dog-3',
    sponsorName: 'Maria Costa',
    sponsorEmail: 'maria.costa@exemplo.com',
    monthlyAmount: 25,
    status: 'active',
    startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spons-4',
    dogId: 'dog-5',
    sponsorName: 'Pedro Fonseca',
    sponsorEmail: 'pedro.f@exemplo.com',
    monthlyAmount: 20,
    status: 'active',
    startDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const mockUpdates: DogUpdate[] = [
  {
    id: 'update-1',
    dogId: 'dog-1',
    title: 'O Max está a dar-se muito bem com as gotas!',
    content: 'Graças aos seus padrinhos, conseguimos comprar um stock de medicação ocular para três meses. O seu olho esquerdo está muito menos inflamado e o veterinário diz que a pressão está estável. O Max comemorou a brincar com a sua bola de ténis favorita no quintal hoje!',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'update-2',
    dogId: 'dog-3',
    title: 'Primeira sessão de fisioterapia do Rocky',
    content: 'O Rocky fez a sua primeira sessão na passadeira aquática hoje! Estava um pouco hesitante no início, mas com alguns biscoitos de frango, portou-se lindamente. O terapeuta diz que ele já apoia cerca de 30% mais peso na patinha. Estamos muito gratos a todos os que apoiam a sua recuperação.',
    imageUrl: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&q=80&w=800',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'update-3',
    dogId: 'dog-5',
    title: 'Chegou a ração especial da Bella!',
    content: 'A ração especial hipoalergénica da Bella já chegou. Já conseguimos ver uma grande melhoria na pele dela – está a coçar-se muito menos e o pelo está a começar a crescer de novo nas zonas secas. Muito obrigado ao padrinho Pedro por ajudá-la!',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
