import type { Dog, DogUpdate, Sponsorship } from '../types';

export const mockDogs: Dog[] = [
  {
    id: 'dog-1',
    name: 'Max',
    description: 'Max is a happy and energetic golden mix who loves running in the grass and playing catch. He was found abandoned in a rural field. Although he is partially blind in his left eye, he doesn\'t let that stop him from being the friendliest dog in the shelter. He needs a godfather to help cover his daily high-quality food and regular eye drop treatments.',
    breed: 'Golden Retriever Mix',
    age: '3 years',
    gender: 'male',
    status: 'partially_sponsored',
    targetMonthlySponsorship: 30,
    currentMonthlySponsorship: 10,
    mainImageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Daily eye drops for dry eye and pressure management (€15/month).',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dog-2',
    name: 'Luna',
    description: 'Luna is a gentle senior soul who loves sleeping in the sun and slow, peaceful walks. She spent her entire life chained up before being rescued by our shelter. She suffers from severe osteoarthritis in her hips, which makes it painful to walk without medication. Sponsoring Luna will help us buy her daily anti-inflammatory medicine and joint supplements.',
    breed: 'Labrador Retriever Mix',
    age: '8 years',
    gender: 'female',
    status: 'needs_sponsor',
    targetMonthlySponsorship: 40,
    currentMonthlySponsorship: 0,
    mainImageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Daily pain medication and premium joint supplements (€30/month).',
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dog-3',
    name: 'Rocky',
    description: 'Rocky is a brave young pup full of life. He was hit by a car as a stray and suffered a broken femur. Thanks to our emergency fund, he received a successful orthopedic surgery. He is currently recovering and needs regular veterinary checkups and physiotherapy sessions to rebuild his leg strength. Help Rocky walk again!',
    breed: 'Mixed Breed',
    age: '1 year',
    gender: 'male',
    status: 'fully_sponsored',
    targetMonthlySponsorship: 50,
    currentMonthlySponsorship: 50,
    mainImageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Monthly veterinary checkups, X-rays, and physical therapy sessions (€45/month).',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dog-4',
    name: 'Toby',
    description: 'Toby was rescued from a hoarding situation with 20 other dogs. As a result, he is extremely fearful of humans and loud noises. He is not ready for adoption yet, but he is working daily with a professional animal behaviorist to learn to trust again. Sponsoring Toby helps pay for his specialized training and anxiety-relief pheromone collars.',
    breed: 'Beagle Mix',
    age: '5 years',
    gender: 'male',
    status: 'needs_sponsor',
    targetMonthlySponsorship: 30,
    currentMonthlySponsorship: 0,
    mainImageUrl: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Weekly sessions with a professional behavioral therapist and calming supplements.',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dog-5',
    name: 'Bella',
    description: 'Bella is a sweet French Bulldog who was surrendered because her previous owners couldn\'t afford her veterinary care. Like many of her breed, she suffers from severe respiratory problems (BOAS) and needs a special diet to prevent chronic skin allergies. She needs a godfather to fund her hypoallergenic prescription diet.',
    breed: 'French Bulldog',
    age: '6 years',
    gender: 'female',
    status: 'partially_sponsored',
    targetMonthlySponsorship: 40,
    currentMonthlySponsorship: 20,
    mainImageUrl: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?auto=format&fit=crop&q=80&w=800',
    medicalNeeds: 'Prescription hypoallergenic diet food (€40/month) and weekly medicated baths.',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const mockSponsorships: Sponsorship[] = [
  {
    id: 'spons-1',
    dogId: 'dog-1',
    sponsorName: 'Ana Silva',
    sponsorEmail: 'ana.silva@example.com',
    monthlyAmount: 10,
    status: 'active',
    startDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spons-2',
    dogId: 'dog-3',
    sponsorName: 'João Santos',
    sponsorEmail: 'joao.santos@example.com',
    monthlyAmount: 25,
    status: 'active',
    startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spons-3',
    dogId: 'dog-3',
    sponsorName: 'Maria Costa',
    sponsorEmail: 'maria.costa@example.com',
    monthlyAmount: 25,
    status: 'active',
    startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spons-4',
    dogId: 'dog-5',
    sponsorName: 'Pedro Fonseca',
    sponsorEmail: 'pedro.f@example.com',
    monthlyAmount: 20,
    status: 'active',
    startDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const mockUpdates: DogUpdate[] = [
  {
    id: 'update-1',
    dogId: 'dog-1',
    title: 'Max is doing great with his drops!',
    content: 'Thanks to his godparents, we purchased a three-month supply of Max\'s eye medication. His left eye is much less inflamed, and his veterinarian says the pressure is stable. Max celebrated by playing extra long with his favorite tennis ball in the yard today!',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'update-2',
    dogId: 'dog-3',
    title: 'Rocky\'s first physical therapy session',
    content: 'Rocky had his first session on the underwater treadmill today! He was a bit hesitant at first, but with some chicken treats, he did fantastic. The therapist says he is placing about 30% more weight on his leg now. We are so grateful to everyone sponsoring his recovery.',
    imageUrl: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&q=80&w=800',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'update-3',
    dogId: 'dog-5',
    title: 'New food arrived for Bella!',
    content: 'Bella\'s prescription hypoallergenic kibble has arrived. We can already see a huge improvement in her skin – she is scratching much less and her fur is starting to grow back in the dry spots. Thank you so much, Pedro, for helping her!',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
